"use strict";
let list = ['China', 'Palestine', 'Iraq', 'Qatar'];
console.log(list);
console.log([...list].sort());
console.log(list);
console.log([...list].sort().reverse());
console.log(list);
console.log(list.reverse());
console.log(list.reverse());
console.log(list.sort());
console.log(list.sort().reverse());
